---
apiVersion: v1
kind: Service
metadata:
  name: svc-ws-service-blue
spec:
  type: LoadBalancer
  selector:
    app: ws-service
    deployment: blue
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80